name: Build Release
on:
  push:
    tags:
      - v*

jobs:
  build-releases:
    strategy:
      matrix:
        arch:
          [
            "linux/amd64 x86_64",
            "linux/arm64/v8 aarch64",
          ]
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: build latest runc
        run: |
          sudo apt-get install libseccomp-dev
          git clone https://github.com/opencontainers/runc
          cd runc
          make
          sudo make install
      - name: Read info
        id: tags
        shell: bash
        run: |
          arch="${{ matrix.arch }}"
          echo ::set-output name=PLATFORM::${arch%% *}
          echo ::set-output name=ARCH::${arch##* }
      - name: Build ${{ matrix.arch }} release
        shell: bash
        run: |
          arch="${{ matrix.arch }}"
          PLATFORM=${arch%% *}
          ARCH=${arch##* }
          mkdir artifacts
          docker build --tag paru:$ARCH .
          docker create --name paru-$ARCH paru:$ARCH
          docker cp paru-$ARCH:/app/paru.tar.zst paru-$ARCH.tar.zst
          docker container rm paru-$ARCH
          mv paru-*.tar.zst artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: paru-${{ steps.tags.outputs.arch }}
          path: artifacts

  create_release:
    name: Create release from this build
    needs: [build-releases]
    runs-on: ubuntu-latest
    steps:
      - name: Read info
        id: tags
        shell: bash
        run: |
          echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
      - uses: actions/download-artifact@v2
        with:
          name: paru-x86_64
      - uses: actions/download-artifact@v2
        with:
          name: paru-aarch64
      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tags.outputs.tag }}
          release_name: ${{ steps.tags.outputs.tag }}
          draft: true
          prerelease: false
      - name: Upload x86_64 asset
        id: upload-release-asset-x86_64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./paru-x86_64.tar.zst
          asset_name: paru-${{ steps.tags.outputs.tag }}-x86_64.tar.zst
          asset_content_type: application/tar+zstd
      - name: Upload aarch64 asset
        id: upload-release-asset-aarch64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./paru-aarch64.tar.zst
          asset_name: paru-${{ steps.tags.outputs.tag }}-aarch64.tar.zst
          asset_content_type: application/tar+zstd